### ISSUE TITLE
DenseMoE, logic as intended inthe article?

### ISSUE THREAD

**Issue by Esaada** [eminorhan/mixture-of-experts#1]
Hi thanks for your code, I'm wondering maybe I'm missing something.
The gating network supposes to tell me which experts to activate, and only then compute their output.
But In your case, it looks like all the experts are computing their output, and only then the gating chooses which expert she "needs".
which is off course not making any sense, because if we have 2048 experts, just bringing them from the dram will take forever.

Or I'm misunderstanding the code??
Please help me understand.

**Comment by eminorhan** [comment]
I assume by "the article", you mean the ["sparsely-gated mixture-of-experts layer"](https://arxiv.org/abs/1701.06538) paper. The code here doesn't implement the model in that paper. The code here implements a densely gated MoE model, as described on the README page. So, as you pointed out, if you try to run the code with a large number of experts, you'll run into memory issues.
